generator:
  class: sfDoctrineGenerator
  param:
    model_class:           GenDesc
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          gen_desc
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: General Description Management
        display: [title]
      filter:  ~
      form:    ~
      edit:
        title: Editing General Description '%%title%%'
      new:
        title: General Description Creation
