<?php

/**
 * BasePeriod
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property clob $description
 * @property integer $days
 * @property Doctrine_Collection $Plan
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getTitle()       Returns the current record's "title" value
 * @method clob                getDescription() Returns the current record's "description" value
 * @method integer             getDays()        Returns the current record's "days" value
 * @method Doctrine_Collection getPlan()        Returns the current record's "Plan" collection
 * @method Period              setId()          Sets the current record's "id" value
 * @method Period              setTitle()       Sets the current record's "title" value
 * @method Period              setDescription() Sets the current record's "description" value
 * @method Period              setDays()        Sets the current record's "days" value
 * @method Period              setPlan()        Sets the current record's "Plan" collection
 * 
 * @package    supra
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePeriod extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('period');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('days', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Plan', array(
             'local' => 'id',
             'foreign' => 'period_id'));
    }
}