<?php

/**
 * BaseDeductionsLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $account_id
 * @property timestamp $deduced_on
 * @property Account $Account
 * 
 * @method integer       getId()         Returns the current record's "id" value
 * @method integer       getAccountId()  Returns the current record's "account_id" value
 * @method timestamp     getDeducedOn()  Returns the current record's "deduced_on" value
 * @method Account       getAccount()    Returns the current record's "Account" value
 * @method DeductionsLog setId()         Sets the current record's "id" value
 * @method DeductionsLog setAccountId()  Sets the current record's "account_id" value
 * @method DeductionsLog setDeducedOn()  Sets the current record's "deduced_on" value
 * @method DeductionsLog setAccount()    Sets the current record's "Account" value
 * 
 * @package    supra
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDeductionsLog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('deductions_log');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('account_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('deduced_on', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Account', array(
             'local' => 'account_id',
             'foreign' => 'id'));
    }
}