<?php

/**
 * BaseBugComment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $bug_id
 * @property integer $staff_id
 * @property string $title
 * @property clob $comment
 * @property Bug $Bug
 * @property Staff $Staff
 * 
 * @method integer    getId()       Returns the current record's "id" value
 * @method integer    getBugId()    Returns the current record's "bug_id" value
 * @method integer    getStaffId()  Returns the current record's "staff_id" value
 * @method string     getTitle()    Returns the current record's "title" value
 * @method clob       getComment()  Returns the current record's "comment" value
 * @method Bug        getBug()      Returns the current record's "Bug" value
 * @method Staff      getStaff()    Returns the current record's "Staff" value
 * @method BugComment setId()       Sets the current record's "id" value
 * @method BugComment setBugId()    Sets the current record's "bug_id" value
 * @method BugComment setStaffId()  Sets the current record's "staff_id" value
 * @method BugComment setTitle()    Sets the current record's "title" value
 * @method BugComment setComment()  Sets the current record's "comment" value
 * @method BugComment setBug()      Sets the current record's "Bug" value
 * @method BugComment setStaff()    Sets the current record's "Staff" value
 * 
 * @package    supra
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBugComment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('bug_comment');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('bug_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('staff_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('comment', 'clob', null, array(
             'type' => 'clob',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Bug', array(
             'local' => 'bug_id',
             'foreign' => 'id'));

        $this->hasOne('Staff', array(
             'local' => 'staff_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}