<?php

/**
 * BaseStaffTaskWork
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $staff_id
 * @property integer $task_work_id
 * @property Staff $Staff
 * @property TaskWork $TaskWork
 * 
 * @method integer       getStaffId()      Returns the current record's "staff_id" value
 * @method integer       getTaskWorkId()   Returns the current record's "task_work_id" value
 * @method Staff         getStaff()        Returns the current record's "Staff" value
 * @method TaskWork      getTaskWork()     Returns the current record's "TaskWork" value
 * @method StaffTaskWork setStaffId()      Sets the current record's "staff_id" value
 * @method StaffTaskWork setTaskWorkId()   Sets the current record's "task_work_id" value
 * @method StaffTaskWork setStaff()        Sets the current record's "Staff" value
 * @method StaffTaskWork setTaskWork()     Sets the current record's "TaskWork" value
 * 
 * @package    supra
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStaffTaskWork extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('staff_task_work');
        $this->hasColumn('staff_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 8,
             ));
        $this->hasColumn('task_work_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Staff', array(
             'local' => 'staff_id',
             'foreign' => 'id'));

        $this->hasOne('TaskWork', array(
             'local' => 'task_work_id',
             'foreign' => 'id'));
    }
}