<?php

/**
 * BaseDeduction
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $account_invoice_id
 * @property string $title
 * @property clob $description
 * @property decimal $deduction
 * @property boolean $approved
 * @property AccountInvoice $AccountInvoice
 * 
 * @method integer        getId()                 Returns the current record's "id" value
 * @method integer        getAccountInvoiceId()   Returns the current record's "account_invoice_id" value
 * @method string         getTitle()              Returns the current record's "title" value
 * @method clob           getDescription()        Returns the current record's "description" value
 * @method decimal        getDeduction()          Returns the current record's "deduction" value
 * @method boolean        getApproved()           Returns the current record's "approved" value
 * @method AccountInvoice getAccountInvoice()     Returns the current record's "AccountInvoice" value
 * @method Deduction      setId()                 Sets the current record's "id" value
 * @method Deduction      setAccountInvoiceId()   Sets the current record's "account_invoice_id" value
 * @method Deduction      setTitle()              Sets the current record's "title" value
 * @method Deduction      setDescription()        Sets the current record's "description" value
 * @method Deduction      setDeduction()          Sets the current record's "deduction" value
 * @method Deduction      setApproved()           Sets the current record's "approved" value
 * @method Deduction      setAccountInvoice()     Sets the current record's "AccountInvoice" value
 * 
 * @package    supra
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDeduction extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('deduction');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('account_invoice_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('deduction', 'decimal', null, array(
             'type' => 'decimal',
             ));
        $this->hasColumn('approved', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AccountInvoice', array(
             'local' => 'account_invoice_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}