<?php

/**
 * BaseAccountPlan
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $account_id
 * @property integer $plan_id
 * @property Account $Account
 * @property Plan $Plan
 * 
 * @method integer     getAccountId()  Returns the current record's "account_id" value
 * @method integer     getPlanId()     Returns the current record's "plan_id" value
 * @method Account     getAccount()    Returns the current record's "Account" value
 * @method Plan        getPlan()       Returns the current record's "Plan" value
 * @method AccountPlan setAccountId()  Sets the current record's "account_id" value
 * @method AccountPlan setPlanId()     Sets the current record's "plan_id" value
 * @method AccountPlan setAccount()    Sets the current record's "Account" value
 * @method AccountPlan setPlan()       Sets the current record's "Plan" value
 * 
 * @package    supra
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAccountPlan extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('account_plan');
        $this->hasColumn('account_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('plan_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Account', array(
             'local' => 'account_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('Plan', array(
             'local' => 'plan_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}