<?php

/**
 * BaseTaskWork
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property decimal $rate
 * @property clob $description
 * @property Doctrine_Collection $StaffTaskWork
 * @property Doctrine_Collection $AccountRate
 * @property Doctrine_Collection $Task
 * @property Doctrine_Collection $TaskLog
 * 
 * @method integer             getId()            Returns the current record's "id" value
 * @method string              getName()          Returns the current record's "name" value
 * @method decimal             getRate()          Returns the current record's "rate" value
 * @method clob                getDescription()   Returns the current record's "description" value
 * @method Doctrine_Collection getStaffTaskWork() Returns the current record's "StaffTaskWork" collection
 * @method Doctrine_Collection getAccountRate()   Returns the current record's "AccountRate" collection
 * @method Doctrine_Collection getTask()          Returns the current record's "Task" collection
 * @method Doctrine_Collection getTaskLog()       Returns the current record's "TaskLog" collection
 * @method TaskWork            setId()            Sets the current record's "id" value
 * @method TaskWork            setName()          Sets the current record's "name" value
 * @method TaskWork            setRate()          Sets the current record's "rate" value
 * @method TaskWork            setDescription()   Sets the current record's "description" value
 * @method TaskWork            setStaffTaskWork() Sets the current record's "StaffTaskWork" collection
 * @method TaskWork            setAccountRate()   Sets the current record's "AccountRate" collection
 * @method TaskWork            setTask()          Sets the current record's "Task" collection
 * @method TaskWork            setTaskLog()       Sets the current record's "TaskLog" collection
 * 
 * @package    supra
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTaskWork extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('task_work');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('rate', 'decimal', null, array(
             'type' => 'decimal',
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('StaffTaskWork', array(
             'local' => 'id',
             'foreign' => 'task_work_id'));

        $this->hasMany('AccountRate', array(
             'local' => 'id',
             'foreign' => 'task_work_id'));

        $this->hasMany('Task', array(
             'local' => 'id',
             'foreign' => 'task_work_id'));

        $this->hasMany('TaskLog', array(
             'local' => 'id',
             'foreign' => 'task_work_id'));
    }
}