<?php

/**
 * BaseAccount
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $client_id
 * @property string $domain_name
 * @property clob $description
 * @property boolean $active
 * @property Client $Client
 * @property Doctrine_Collection $AccountInvoice
 * @property Doctrine_Collection $AccountRecord
 * @property Doctrine_Collection $Bug
 * 
 * @method integer             getId()             Returns the current record's "id" value
 * @method integer             getClientId()       Returns the current record's "client_id" value
 * @method string              getDomainName()     Returns the current record's "domain_name" value
 * @method clob                getDescription()    Returns the current record's "description" value
 * @method boolean             getActive()         Returns the current record's "active" value
 * @method Client              getClient()         Returns the current record's "Client" value
 * @method Doctrine_Collection getAccountInvoice() Returns the current record's "AccountInvoice" collection
 * @method Doctrine_Collection getAccountRecord()  Returns the current record's "AccountRecord" collection
 * @method Doctrine_Collection getBug()            Returns the current record's "Bug" collection
 * @method Account             setId()             Sets the current record's "id" value
 * @method Account             setClientId()       Sets the current record's "client_id" value
 * @method Account             setDomainName()     Sets the current record's "domain_name" value
 * @method Account             setDescription()    Sets the current record's "description" value
 * @method Account             setActive()         Sets the current record's "active" value
 * @method Account             setClient()         Sets the current record's "Client" value
 * @method Account             setAccountInvoice() Sets the current record's "AccountInvoice" collection
 * @method Account             setAccountRecord()  Sets the current record's "AccountRecord" collection
 * @method Account             setBug()            Sets the current record's "Bug" collection
 * 
 * @package    supra
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAccount extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('account');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('client_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('domain_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('active', 'boolean', null, array(
             'type' => 'boolean',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Client', array(
             'local' => 'client_id',
             'foreign' => 'id'));

        $this->hasMany('AccountInvoice', array(
             'local' => 'id',
             'foreign' => 'account_id'));

        $this->hasMany('AccountRecord', array(
             'local' => 'id',
             'foreign' => 'account_id'));

        $this->hasMany('Bug', array(
             'local' => 'id',
             'foreign' => 'account_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}