<?php

/**
 * BaseAccountRecord
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $account_id
 * @property string $name
 * @property clob $description
 * @property Account $Account
 * 
 * @method integer       getId()          Returns the current record's "id" value
 * @method integer       getAccountId()   Returns the current record's "account_id" value
 * @method string        getName()        Returns the current record's "name" value
 * @method clob          getDescription() Returns the current record's "description" value
 * @method Account       getAccount()     Returns the current record's "Account" value
 * @method AccountRecord setId()          Sets the current record's "id" value
 * @method AccountRecord setAccountId()   Sets the current record's "account_id" value
 * @method AccountRecord setName()        Sets the current record's "name" value
 * @method AccountRecord setDescription() Sets the current record's "description" value
 * @method AccountRecord setAccount()     Sets the current record's "Account" value
 * 
 * @package    supra
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAccountRecord extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('account_record');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('account_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Account', array(
             'local' => 'account_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}