<?php

/**
 * BaseTestClient
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property clob $track_record
 * 
 * @method clob       getTrackRecord()  Returns the current record's "track_record" value
 * @method TestClient setTrackRecord()  Sets the current record's "track_record" value
 * 
 * @package    supra
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTestClient extends sfGuardUser
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('test_client');
        $this->hasColumn('track_record', 'clob', null, array(
             'type' => 'clob',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}