<?php

/**
 * BaseTaskPriority
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property clob $description
 * @property Doctrine_Collection $Task
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getName()        Returns the current record's "name" value
 * @method clob                getDescription() Returns the current record's "description" value
 * @method Doctrine_Collection getTask()        Returns the current record's "Task" collection
 * @method TaskPriority        setId()          Sets the current record's "id" value
 * @method TaskPriority        setName()        Sets the current record's "name" value
 * @method TaskPriority        setDescription() Sets the current record's "description" value
 * @method TaskPriority        setTask()        Sets the current record's "Task" collection
 * 
 * @package    supra
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTaskPriority extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('task_priority');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Task', array(
             'local' => 'id',
             'foreign' => 'task_priority_id'));
    }
}