<?php

/**
 * BaseStaff
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property string $firstname
 * @property string $lastname
 * @property string $title
 * @property clob $bio
 * @property sfGuardUser $User
 * @property Doctrine_Collection $Bug
 * @property Doctrine_Collection $BugComment
 * 
 * @method integer             getId()         Returns the current record's "id" value
 * @method integer             getUserId()     Returns the current record's "user_id" value
 * @method string              getFirstname()  Returns the current record's "firstname" value
 * @method string              getLastname()   Returns the current record's "lastname" value
 * @method string              getTitle()      Returns the current record's "title" value
 * @method clob                getBio()        Returns the current record's "bio" value
 * @method sfGuardUser         getUser()       Returns the current record's "User" value
 * @method Doctrine_Collection getBug()        Returns the current record's "Bug" collection
 * @method Doctrine_Collection getBugComment() Returns the current record's "BugComment" collection
 * @method Staff               setId()         Sets the current record's "id" value
 * @method Staff               setUserId()     Sets the current record's "user_id" value
 * @method Staff               setFirstname()  Sets the current record's "firstname" value
 * @method Staff               setLastname()   Sets the current record's "lastname" value
 * @method Staff               setTitle()      Sets the current record's "title" value
 * @method Staff               setBio()        Sets the current record's "bio" value
 * @method Staff               setUser()       Sets the current record's "User" value
 * @method Staff               setBug()        Sets the current record's "Bug" collection
 * @method Staff               setBugComment() Sets the current record's "BugComment" collection
 * 
 * @package    supra
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStaff extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('staff');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('user_id', 'integer', 255, array(
             'type' => 'integer',
             'length' => 255,
             ));
        $this->hasColumn('firstname', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('lastname', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('bio', 'clob', null, array(
             'type' => 'clob',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasMany('Bug', array(
             'local' => 'id',
             'foreign' => 'staff_id'));

        $this->hasMany('BugComment', array(
             'local' => 'id',
             'foreign' => 'staff_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}