<?php

/**
 * BaseAccountInvoiceDeduction
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $account_invoice_id
 * @property integer $deduction_id
 * @property AccountInvoice $AccountInvoice
 * @property Deduction $Deduction
 * 
 * @method integer                 getAccountInvoiceId()   Returns the current record's "account_invoice_id" value
 * @method integer                 getDeductionId()        Returns the current record's "deduction_id" value
 * @method AccountInvoice          getAccountInvoice()     Returns the current record's "AccountInvoice" value
 * @method Deduction               getDeduction()          Returns the current record's "Deduction" value
 * @method AccountInvoiceDeduction setAccountInvoiceId()   Sets the current record's "account_invoice_id" value
 * @method AccountInvoiceDeduction setDeductionId()        Sets the current record's "deduction_id" value
 * @method AccountInvoiceDeduction setAccountInvoice()     Sets the current record's "AccountInvoice" value
 * @method AccountInvoiceDeduction setDeduction()          Sets the current record's "Deduction" value
 * 
 * @package    supra
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAccountInvoiceDeduction extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('account_invoice_deduction');
        $this->hasColumn('account_invoice_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 8,
             ));
        $this->hasColumn('deduction_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AccountInvoice', array(
             'local' => 'account_invoice_id',
             'foreign' => 'id'));

        $this->hasOne('Deduction', array(
             'local' => 'deduction_id',
             'foreign' => 'id'));
    }
}