<?php

/**
 * BaseGenDesc
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property clob $description
 * @property Doctrine_Collection $TaskLog
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getTitle()       Returns the current record's "title" value
 * @method clob                getDescription() Returns the current record's "description" value
 * @method Doctrine_Collection getTaskLog()     Returns the current record's "TaskLog" collection
 * @method GenDesc             setId()          Sets the current record's "id" value
 * @method GenDesc             setTitle()       Sets the current record's "title" value
 * @method GenDesc             setDescription() Sets the current record's "description" value
 * @method GenDesc             setTaskLog()     Sets the current record's "TaskLog" collection
 * 
 * @package    supra
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGenDesc extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('gen_desc');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('title', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('TaskLog', array(
             'local' => 'id',
             'foreign' => 'gen_desc_id'));
    }
}