<?php

/**
 * BaseAccountInvoiceTask
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $account_invoice_id
 * @property integer $task_id
 * @property AccountInvoice $AccountInvoice
 * @property Task $Task
 * 
 * @method integer            getAccountInvoiceId()   Returns the current record's "account_invoice_id" value
 * @method integer            getTaskId()             Returns the current record's "task_id" value
 * @method AccountInvoice     getAccountInvoice()     Returns the current record's "AccountInvoice" value
 * @method Task               getTask()               Returns the current record's "Task" value
 * @method AccountInvoiceTask setAccountInvoiceId()   Sets the current record's "account_invoice_id" value
 * @method AccountInvoiceTask setTaskId()             Sets the current record's "task_id" value
 * @method AccountInvoiceTask setAccountInvoice()     Sets the current record's "AccountInvoice" value
 * @method AccountInvoiceTask setTask()               Sets the current record's "Task" value
 * 
 * @package    supra
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAccountInvoiceTask extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('account_invoice_task');
        $this->hasColumn('account_invoice_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 8,
             ));
        $this->hasColumn('task_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AccountInvoice', array(
             'local' => 'account_invoice_id',
             'foreign' => 'id'));

        $this->hasOne('Task', array(
             'local' => 'task_id',
             'foreign' => 'id'));
    }
}