account_invoice:
  class: sfDoctrineRouteCollection
  options:
    model:                AccountInvoice
    module:               invoice
    prefix_path:          /invoice
    column:               id
    with_wildcard_routes: true

staff:
  class: sfDoctrineRouteCollection
  options:
    model:                Staff
    module:               staff
    prefix_path:          /staff
    column:               id
    with_wildcard_routes: true

client:
  class: sfDoctrineRouteCollection
  options:
    model:                Client
    module:               client
    prefix_path:          /client
    column:               id
    with_wildcard_routes: true

account:
  class: sfDoctrineRouteCollection
  options:
    model:                Account
    module:               account
    prefix_path:          /account
    column:               id
    with_wildcard_routes: true

task:
  class: sfDoctrineRouteCollection
  options:
    model:                Task
    module:               task
    prefix_path:          /task
    column:               id
    with_wildcard_routes: true

task_log:
  class: sfDoctrineRouteCollection
  options:
    model:                TaskLog
    module:               task_log
    prefix_path:          /task_log
    column:               id
    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: task_log, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*

sf_guard_signin:
  url: /login
  param:
    module: sfGuardAuth
    action: signin

sf_guard_signout:
  url: /logout
  param: 
    module: sfGuardAuth
    action: signout

sf_guard_password:
  url: /request_password
  param: 
    module: sfGuardAuth
    action: password

sf_gaurd_user:
  url: /guard/user
  param: 
    module: sfGuardUser

sf_guard_group:
  url: /guard/group
  param: 
    module: sfGuardGroup

sf_guard_permission:
  url: /guard/permission
  param: 
    module: sfGuardPermission
