deduction:
  class: sfDoctrineRouteCollection
  options:
    model:                Deduction
    module:               deduction
    prefix_path:          /deduction
    column:               id
    with_wildcard_routes: true

period:
  class: sfDoctrineRouteCollection
  options:
    model:                Period
    module:               period
    prefix_path:          /period
    column:               id
    with_wildcard_routes: true

plan:
  class: sfDoctrineRouteCollection
  options:
    model:                Plan
    module:               plan
    prefix_path:          /plan
    column:               id
    with_wildcard_routes: true

gen_desc:
  class: sfDoctrineRouteCollection
  options:
    model:                GenDesc
    module:               gen_desc
    prefix_path:          /gen_desc
    column:               id
    with_wildcard_routes: true

task_type:
  class: sfDoctrineRouteCollection
  options:
    model:                TaskType
    module:               task_type
    prefix_path:          /task_type
    column:               id
    with_wildcard_routes: true

task_status:
  class: sfDoctrineRouteCollection
  options:
    model:                TaskStatus
    module:               task_status
    prefix_path:          /task_status
    column:               id
    with_wildcard_routes: true

task_priority:
  class: sfDoctrineRouteCollection
  options:
    model:                TaskPriority
    module:               task_priority
    prefix_path:          /task_priority
    column:               id
    with_wildcard_routes: true

task_work:
  class: sfDoctrineRouteCollection
  options:
    model:                TaskWork
    module:               task_work
    prefix_path:          /task_work
    column:               id
    with_wildcard_routes: true

task_comment:
  class: sfDoctrineRouteCollection
  options:
    model:                TaskComment
    module:               task_comment
    prefix_path:          /task_comment
    column:               id
    with_wildcard_routes: true

account_record:
  class: sfDoctrineRouteCollection
  options:
    model:                AccountRecord
    module:               account_record
    prefix_path:          /account_record
    column:               id
    with_wildcard_routes: true

account_invoice:
  class: sfDoctrineRouteCollection
  options:
    model:                AccountInvoice
    module:               invoice
    prefix_path:          /invoice
    column:               id
    with_wildcard_routes: true

staff:
  class: sfDoctrineRouteCollection
  options:
    model:                Staff
    module:               staff
    prefix_path:          /staff
    column:               id
    with_wildcard_routes: true

client:
  class: sfDoctrineRouteCollection
  options:
    model:                Client
    module:               client
    prefix_path:          /client
    column:               id
    with_wildcard_routes: true

account:
  class: sfDoctrineRouteCollection
  options:
    model:                Account
    module:               account
    prefix_path:          /account
    column:               id
    with_wildcard_routes: true

task:
  class: sfDoctrineRouteCollection
  options:
    model:                Task
    module:               task
    prefix_path:          /task
    column:               id
    with_wildcard_routes: true

task_log:
  class: sfDoctrineRouteCollection
  options:
    model:                TaskLog
    module:               task_log
    prefix_path:          /task_log
    column:               id
    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: task_log, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*

sf_guard_signin:
  url: /login
  param:
    module: sfGuardAuth
    action: signin

sf_guard_signout:
  url: /logout
  param: 
    module: sfGuardAuth
    action: signout

sf_guard_password:
  url: /request_password
  param: 
    module: sfGuardAuth
    action: password

sf_gaurd_user:
  url: /guard/user
  param: 
    module: sfGuardUser

sf_guard_group:
  url: /guard/group
  param: 
    module: sfGuardGroup

sf_guard_permission:
  url: /guard/permission
  param: 
    module: sfGuardPermission
