generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Account
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          account
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Account Management
        display: [=client,title,domain_name]
      filter:  ~
      form:    ~
      edit:
        title: Editing Account '%%title%%'
      new: 
        title: Account Creation
