generator:
  class: sfDoctrineGenerator
  param:
    model_class:           AccountInvoice
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          account_invoice
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Invoice Management
        display: [ref_no,=account,ammount_due,paid_off]
      filter:  ~
      form:    ~
      edit:  
        title: Editing Invoice '%%ref_no%%'
      new:
        title: Invoice Creation

