<?php

/**
 * AccountInvoiceTaskTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AccountInvoiceTaskTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AccountInvoiceTaskTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AccountInvoiceTask');
    }
}