<?php

/**
 * AccountInvoiceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AccountInvoiceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AccountInvoiceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AccountInvoice');
    }
}