<?php

/**
 * AccountRateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AccountRateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AccountRateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AccountRate');
    }
}