<?php

/**
 * AccountRecordTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AccountRecordTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AccountRecordTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AccountRecord');
    }
}