<?php

/**
 * AccountInvoice
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    supra
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class AccountInvoice extends BaseAccountInvoice {

  public function fetchRecent() {
    return Doctirne_Query::create()
             ->from('AccountInvoice ai')
             ->orderBy('ai.updated_at DESC')
             ->limit(5)
             ->execute();
  }

  public function getTotal() {
    $total = 0;
 
    foreach($this->getAccountInvoiceTask() as $inv_task) {
        $task = $inv_task->getTask();
        $work = $task->getTaskWork();
        foreach($task->getTaskLog() as $log) {
            if($log->getHours()) {
                $total += $work->getRate() * $log->getHours();
            }
        }
    }

    return round($total,2);
  }
}
