<?php

/**
 * AccountPlanTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AccountPlanTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AccountPlanTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AccountPlan');
    }
}