<?php

/**
 * AccountInvoice
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    supra
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class AccountInvoice extends BaseAccountInvoice {

  public function fetchRecent() {
    return Doctirne_Query::create()
             ->from('AccountInvoice ai')
             ->orderBy('ai.updated_at DESC')
             ->limit(5)
             ->execute();
  }

  public function getTotal($is_admin = false) {
      $total = 0;

      foreach($this->getAssociatedTasks() as $task) {  
          $work = $task->getTaskWork();
          foreach($task->getTaskLog() as $log) {
              //must be admin to override is_viewable
              if($log->getHours() && ($log->getIsViewable() || $is_admin)) {
                  $total += $work->getRate() * $log->getHours();
              }
          }
      }

      return round($total,2);
  }

  public function getAssociatedTasks() {
      return Doctrine_Core::getTable('Task')->getAllByAccountInvoiceId($this->getId());
  }

  function __toString() {

      return $this->getAccount() . ' - ' . $this->getRefNo();

  }
}
