<?php

/**
 * BugCommentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BugCommentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BugCommentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BugComment');
    }
}