<?php

/**
 * BugPriorityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BugPriorityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BugPriorityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BugPriority');
    }
}