<?php

/**
 * BugStatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BugStatusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BugStatusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BugStatus');
    }
}