<?php

/**
 * BugTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BugTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BugTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BugType');
    }
}