<?php

/**
 * Client
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    supra
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Client extends BaseClient
{
  public function getFullName() {
      return $this->firstname . ' ' . $this->lastname;

  }

  function __toString() {
      return $this->getFullName();
  }
}
