<?php

/**
 * Client
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    supra
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Client extends BaseClient
{
    public static function getLoggedIn() {
      $currentUser = sfContext::getInstance()->getUser();

      $q = Doctrine_Query::create()
      ->from('Client c')
      ->where('c.user_id = ?',$currentUser->getId());

      return $q;
    }

    public static function loggedIn() {
      return Client::getLoggedIn()->fetchOne();
    }

    public static function loggedInId() {
      return Client::getLoggedIn()->fetchOne()->id;
    }


  public function getFullName() {
      return $this->getUser()->first_name . ' ' . $this->getUser()->last_name;

  }

  function __toString() {
      return $this->getFullName();
  }
}
