<?php

/**
 * ClientTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClientTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClientTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Client');
    }

    public function getByUserId($user_id) {

        return Doctrine_Query::create()
               ->from('Client c')
               ->where('c.user_id = ?',$user_id)
               ->limit(1)
               ->fetchOne();

    }

    public static function loggedIn() {
      $currentUser = sfContext::getInstance()->getUser();

      $q = Doctrine_Query::create()
      ->select('c.id')
      ->from('Client c')
      ->where('c.user_id = ?',$currentUser->getId())
      ->fetchOne()->id;

      return $q;
    }


    public function queryAccounts($client_id) {

        return Doctrine_Query::create()
        ->from('Account a')
        ->where('a.client_id = ?',$client_id);

    }
}
