<?php

/**
 * CredentialTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CredentialTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CredentialTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CredentialType');
    }
}