<?php

/**
 * DeductionsLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DeductionsLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DeductionsLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DeductionsLog');
    }
}