<?php

/**
 * DeductionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DeductionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DeductionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Deduction');
    }
}