<?php

/**
 * GenDescTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GenDescTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GenDescTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GenDesc');
    }
}