<?php

/**
 * Staff
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    supra
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Staff extends BaseStaff {

    public function getStaffName() {
        return $this->firstname . ' ' . $this->lastname;
    }

    private function getTaskLogs() {
      return  Doctrine_Core::getTable('TaskLog')
        ->createQuery('a')
        ->where('a.staff_id = ?', $this->id);
    }

    public function getTaskLogsByStaffId() {
      return  $this->getTaskLogs()->execute();
    }

    public function countTaskLogsByStaffId() {
      return  $this->getTaskLogs()->count();
    }

    public function getTasksByStaffId() {
      return Doctrine_Query::create()
        ->from('Task t')
        ->where('t.staff_id = ?', $this->id);
    }

    public function countCompleteTasksByStaffId() {
      return $this->getTasksByStaffId()
        ->andWhere('t.task_status_id = ?', 3)->count();
    }

    public function countIncompleteTasksByStaffId() {
       return $this->getTasksByStaffId()
         ->andWhere('t.task_status_id <> ?', 3)->count();
    }

    function __toString() {
      return $this->getStaffName();
    }
}
