<?php

/**
 * StaffTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StaffTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StaffTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Staff');
    }

    public function retrieveAssociatedUser(Doctrine_Query $q) {
      $rootAlias = $q->getRootAlias();
      $q->leftJoin($rootAlias . '.User u');
      return $q;
    }

}
