<?php

/**
 * TaskStatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TaskStatusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TaskStatusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TaskStatus');
    }
}