<?php

/**
 * TaskTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TaskTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TaskTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Task');
    }

    public function queryAll($sort) {
        return Doctrine_Query::Create()
               ->from('Task t')
               ->orderBy('t.'.$sort);
    }

    public function queryAllByStaffId($sort) {

        return Doctrine_Query::Create()
        ->from('Task t')
        ->where('t.staff_id = ?',Staff::loggedInId())
        ->orderBy('t.'.$sort);

    }

    public function queryIncomplete($sort) {
        return Doctrine_Query::Create()
               ->from('Task t')
               ->where('t.task_status_id <> ?',3)
               ->orderBy('t.'.$sort);
    }

    public function queryIncompleteByStaffId($sort) {

        return Doctrine_Query::Create() 
        ->from('Task t')
        ->where('t.staff_id = ?',Staff::loggedInId())
        ->andWhere('t.task_status_id <> ?',3)
        ->orderBy('t.'.$sort);

    }
}
