<?php

/**
 * TaskPriorityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TaskPriorityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TaskPriorityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TaskPriority');
    }
}