<?php

/**
 * TaskLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TaskLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TaskLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TaskLog');
    }
}