<?php

/**
 * TaskWorkTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TaskWorkTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TaskWorkTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TaskWork');
    }
}