<?php

/**
 * TaskCommentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TaskCommentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TaskCommentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TaskComment');
    }
}