<?php

/**
 * Task
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    supra
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Task extends BaseTask {


    public function isEntitled() {

        return Doctrine_Query::Create()
        ->from('Task t')
        ->where('t.created_by = ?',myUser::getLoggedIn()->getId())
        ->andWhere('t.id = ?',$this->getId())
        ->orWhere('t.user_id = ?',myUser::getLoggedIn()->getId())
        ->andWhere('t.id = ?',$this->getId())
        ->limit(1)
        ->fetchOne();

    }

}
