<?php

/**
 * TaskTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TaskTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TaskTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Task');
    }

    public function getByStaffId() {

        return Doctrine_Query::Create() 
        ->from('Task t')
        ->where('t.staff_id = ?',Staff::loggedInId())
        ->execute();

    }
}
