<?php

/**
 * TestClientTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TestClientTable extends sfGuardUserTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object TestClientTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TestClient');
    }
}