<?php

/**
 * TimeLogTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TimeLogTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TimeLogTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TimeLogType');
    }
}