<?php

/**
 * TimeLogType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    supra
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class TimeLogType extends BaseTimeLogType
{

    public static function getClockInById($id) {
        $tlt = Doctrine::getTable('TimeLogType')->find($id);
        return $tlt->clock_in;
    }

}
