<?php

/**
 * TimeLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    supra
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class TimeLog extends BaseTimeLog
{

    public static function getLastByStaffId($staff_id) {
        return Doctrine_Query::create()
        ->from('TimeLog t')
        ->where('t.staff_id = ?', $staff_id)
        ->orderBy('t.time DESC')
        ->limit(1)
        ->fetchOne();
    }

}
