<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/06/06 06:05:17

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=supra',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
