<?php
// auto-generated by sfSecurityConfigHandler
// date: 2012/06/06 06:05:59
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 'superadmin',
    ),
  ),
);
