<?php
// auto-generated by sfSecurityConfigHandler
// date: 2012/04/29 02:22:57
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 'superadmin',
    ),
  ),
);
