generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Period
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          period
    with_doctrine_route:   true
    actions_base_class:    sfActions


    config:
      actions: ~
      fields:  ~
      list:
        title: Period Management
        display: [title]
      filter:  ~
      form:    ~
      edit:
        title: Editing Period '%%title%%'
      new:
        title: Period Creation
