generator:
  class: sfDoctrineGenerator
  param:
    model_class:           TaskLog
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          task_log
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        task_work_id:
          label: Work Type
        task_work:
          label: Work Type
      list:
        title: Log Management
        display: [title,staff_name,task,task_work]
      filter: 
      form:   
        display: 
      edit:
        title: Editing Log '%%title%%'

      new:
        title: Log Creation

