generator:
  class: sfDoctrineGenerator
  param:
    model_class:           TimeLogType
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          time_log_type
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Time Log Type Management
        display: [=name,clock_in]
      filter:  ~
      form:    ~
      edit:
        title: Modifying Time Log Type '%%name%%'
      new:
        title: Time Log Type Creation
