generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Deduction
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          deduction
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Deduction Management
        display: [title,deduction,approved]
      filter:  ~
      form:    ~
      edit:
        title: Editing Deduction '%%title%%'
      new:
        title: Deduction Creation
