generator:
  class: sfDoctrineGenerator
  param:
    model_class:           TaskComment
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          task_comment
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:  
        title: Comment Management
        display: [title,task,staff]
      filter:  ~
      form:    ~
      edit:
        title: Editing Comment '%%title%%'
      new:
        title: Comment Creation
