generator:
  class: sfDoctrineGenerator
  param:
    model_class:           TaskPriority
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          task_priority
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Priority Type Management
        display: [name]
      filter:  ~
      form:    ~
      edit:
        title: Editing Priority Type '%%name%%'
      new:
        title: Priority Type Creation
