<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version6 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('account', 'account_plan_id_plan_id', array(
             'name' => 'account_plan_id_plan_id',
             'local' => 'plan_id',
             'foreign' => 'id',
             'foreignTable' => 'plan',
             ));
        $this->createForeignKey('account_plan', 'account_plan_account_id_account_id', array(
             'name' => 'account_plan_account_id_account_id',
             'local' => 'account_id',
             'foreign' => 'id',
             'foreignTable' => 'account',
             ));
        $this->createForeignKey('account_plan', 'account_plan_plan_id_plan_id', array(
             'name' => 'account_plan_plan_id_plan_id',
             'local' => 'plan_id',
             'foreign' => 'id',
             'foreignTable' => 'plan',
             ));
        $this->createForeignKey('deductions_log', 'deductions_log_account_id_account_id', array(
             'name' => 'deductions_log_account_id_account_id',
             'local' => 'account_id',
             'foreign' => 'id',
             'foreignTable' => 'account',
             ));
        $this->createForeignKey('plan', 'plan_period_id_period_id', array(
             'name' => 'plan_period_id_period_id',
             'local' => 'period_id',
             'foreign' => 'id',
             'foreignTable' => 'period',
             ));
        $this->addIndex('account', 'account_plan_id', array(
             'fields' => 
             array(
              0 => 'plan_id',
             ),
             ));
        $this->addIndex('account_plan', 'account_plan_account_id', array(
             'fields' => 
             array(
              0 => 'account_id',
             ),
             ));
        $this->addIndex('account_plan', 'account_plan_plan_id', array(
             'fields' => 
             array(
              0 => 'plan_id',
             ),
             ));
        $this->addIndex('deductions_log', 'deductions_log_account_id', array(
             'fields' => 
             array(
              0 => 'account_id',
             ),
             ));
        $this->addIndex('plan', 'plan_period_id', array(
             'fields' => 
             array(
              0 => 'period_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('account', 'account_plan_id_plan_id');
        $this->dropForeignKey('account_plan', 'account_plan_account_id_account_id');
        $this->dropForeignKey('account_plan', 'account_plan_plan_id_plan_id');
        $this->dropForeignKey('deductions_log', 'deductions_log_account_id_account_id');
        $this->dropForeignKey('plan', 'plan_period_id_period_id');
        $this->removeIndex('account', 'account_plan_id', array(
             'fields' => 
             array(
              0 => 'plan_id',
             ),
             ));
        $this->removeIndex('account_plan', 'account_plan_account_id', array(
             'fields' => 
             array(
              0 => 'account_id',
             ),
             ));
        $this->removeIndex('account_plan', 'account_plan_plan_id', array(
             'fields' => 
             array(
              0 => 'plan_id',
             ),
             ));
        $this->removeIndex('deductions_log', 'deductions_log_account_id', array(
             'fields' => 
             array(
              0 => 'account_id',
             ),
             ));
        $this->removeIndex('plan', 'plan_period_id', array(
             'fields' => 
             array(
              0 => 'period_id',
             ),
             ));
    }
}