<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version1 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('gen_desc', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'title' => 
             array(
              'type' => 'string',
              'length' => '',
             ),
             'description' => 
             array(
              'type' => 'clob',
              'length' => '',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->addColumn('staff', 'is_subcontractor', 'boolean', '25', array(
             'notnull' => '1',
             'default' => '0',
             ));
        $this->addColumn('task_log', 'gen_desc_id', 'integer', '8', array(
             'notnull' => '1',
             ));
        $this->addColumn('task_log', 'staff_comment', 'clob', '', array(
             ));
        $this->addColumn('task_log', 'clock_in', 'timestamp', '25', array(
             ));
        $this->addColumn('task_log', 'clock_out', 'timestamp', '25', array(
             ));
        $this->addColumn('task_log', 'mileage', 'decimal', '18', array(
             ));
        $this->addColumn('task_log', 'percentage', 'integer', '8', array(
             ));
        $this->addColumn('task_log', 'is_billable', 'boolean', '25', array(
             ));
    }

    public function down()
    {
        $this->dropTable('gen_desc');
        $this->removeColumn('staff', 'is_subcontractor');
        $this->removeColumn('task_log', 'gen_desc_id');
        $this->removeColumn('task_log', 'staff_comment');
        $this->removeColumn('task_log', 'clock_in');
        $this->removeColumn('task_log', 'clock_out');
        $this->removeColumn('task_log', 'mileage');
        $this->removeColumn('task_log', 'percentage');
        $this->removeColumn('task_log', 'is_billable');
    }
}