generator:
  class: sfDoctrineGenerator
  param:
    model_class:           CredentialType
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          credential_type
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title:   Account Credential Type Management
        display: [=name]
      filter:  ~
      form:
      edit:
        title: Modifying Account Credential Type '%%name%%'
      new:
        title: Account Credential Type Creation
