generator:
  class: sfDoctrineGenerator
  param:
    model_class:           TaskWork
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          task_work
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Work Types Managment
        display: [name,rate]
      filter:  ~
      form:    ~
      edit:
        title: Edit Work Type '%%name%%'
      new:
        title: Work Type Creation

