generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Credential
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          credential
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Account Credential Management
        display: [=name,credential_type,account]
      filter:  ~
      form:    ~
      edit:
        title: Modifying Account Credential '%%name%%'
      new:
        title: Account Credential Creation
