<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/05/06 11:05:15
sfConfig::add(array(
  'mod_incomplete_task_enabled' => true,
  'mod_incomplete_task_view_class' => 'sfPHP',
));
