<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/06/06 16:04:33
sfConfig::add(array(
  'mod_incomplete_task_enabled' => true,
  'mod_incomplete_task_view_class' => 'sfPHP',
));
