<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/05/01 01:31:33
sfConfig::add(array(
  'mod_incomplete_task_enabled' => true,
  'mod_incomplete_task_view_class' => 'sfPHP',
));
