generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Staff
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          staff
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Employee Management 
        display: [user, title]
        table_method: retrieveAssociatedUser
      filter:  ~
      form:
        display: [User,title,bio,is_subcontractor]
      edit:
        title: Editing Employee '%%User%%'
      new: 
        title: Employee Creation
