detect_relations: true

Client:
  actAs: [Timestampable]
  columns: 
    id:           { type: integer, primary: true, autoincrement: true }
    user_id:      { type: integer(255) }
    track_record: { type: clob }
    
  relations: 
    User:
      class: sfGuardUser
      local: user_id
      foreign: id
      type: one
      foreignType: one
      foreignAlias: Client

Staff:
  actAs: [Timestampable]
  columns:
    id:               { type: integer, primary: true, autoincrement: true }
    user_id:          { type: integer(255) }
    title:            { type: string(255) }
    bio:              { type: clob }
    is_subcontractor: { type: boolean, notnull: true, default: 0 }
  relations:
    User:
      class: sfGuardUser
      local: user_id
      foreign: id
      type: one
      foreignType: one
      foreignAlias: Staff

StaffTaskWork:
  columns:
    staff_id:     { type: integer, notnull: true }
    task_work_id: { type: integer, notnull: true }

Account:
  actAs: [Timestampable]
  columns:
    id:           { type: integer, primary: true, autoincrement: true }
    client_id:    { type: integer }    
    plan_id:      { type: integer }
    title:        { type: string(255) }
    credit:       { type: decimal }
    domain_name:  { type: string(255) }
    description:  { type: clob }
    active:       { type: boolean, notnull: true, default: 0 }

AccountPlan:
  actAs: [Timestampable]
  columns: 
    account_id: { type: integer, notnull: true }
    plan_id:    { type: integer, notnull: true }

Plan:
  columns:
    id:          { type: integer, primary: true, autoincrement: true }
    title:       { type: string(255) }
    description: { type: clob }
    deduction:   { type: decimal }
    period_id:   { type: integer }

Period:
  columns:
    id:          { type: integer, primary: true, autoincrement: true }
    title:       { type: string(255) }
    description: { type: clob }
    days:        { type: integer }

DeductionsLog:
  columns:
    id:          { type: integer, primary: true, autoincrement: true }
    account_id:  { type: intger }
    deduced_on:  { type: timestamp }  

AccountInvoice:
  actAs: [Timestampable]
  columns:
    id:          { type: integer, primary: true, autoincrement: true }
    account_id:  { type: integer }
    ref_no:      { type: string(255), unique: true }
    ammount_due: { type: decimal }
    description: { type: clob }
    paid_off:    { type: boolean, notnull: true, default: 0 }

AccountInvoiceTask:
  columns: 
    account_invoice_id: { type: integer, notnull: true }
    task_id :           { type: integer, notnull: true }

AccountRecord:
  actAs: [Timestampable]
  columns: 
    id:          { type: integer, primary: true, autoincrement: true }
    account_id:  { type: integer }
    name:        { type: string(255), notnull: true }
    description: { type: clob }

Task:
  actAs: [Timestampable]
  columns: 
    id:               { type: integer, primary: true, autoincrement: true }
    account_id:       { type: integer, notnull: true }
    staff_id:         { type: integer } 
    task_status_id:   { type: integer, notnull: true }
    task_type_id:     { type: integer, notnull: true }
    task_priority_id: { type: integer, notnull: true }
    task_work_id:     { type: integer, notnull: true }
    ref_no:           { type: string(255), unique: true }
    name:             { type: string(255) }
    description:      { type: clob } 

TaskStatus:
  columns:
    id:           { type: integer, primary: true, autoincrement: true }
    name:         { type: string(255) }

TaskType:
  columns:
    id:           { type: integer, primary: true, autoincrement: true }
    name:         { type: string(255) }

TaskPriority:
  columns:
    id:           { type: integer, primary: true, autoincrement: true }
    name:         { type: string(255) }

TaskWork:
  columns:
    id:           { type: integer, primary: true, autoincrement: true }
    name:         { type: string(255) }
    rate:         { type: decimal }
    description:  { type: clob }

TaskComment:
  actAs: [Timestampable] 
  columns:
    id:           { type: integer, primary: true, autoincrement: true }
    task_id:      { type: integer, notnull: true }
    staff_id:     { type: integer, notnull: true } 
    title:        { type: string(255) }
    comment:      { type: clob }

TaskLog:
  actAs: [Timestampable]
  columns:
    id:            { type: integer, primary: true, autoincrement: true }
    task_id:       { type: integer, notnull: true }
    task_work_id:  { type: integer, notnull: true }
    staff_id:      { type: integer, notnull: true }
    title:         { type: string(255) }
    description:   { type: clob }
    gen_desc_id:   { type: integer }
    staff_comment: { type: clob }
    clock_in:      { type: timestamp }
    clock_out:     { type: timestamp } 
    hours_logged:  { type: decimal }
    mileage:       { type: decimal }
    percentage:    { type: integer }
    is_billable:   { type: boolean }
    
GenDesc:
  columns:
    id:            { type:integer, primary: true, autoincrement: true }
    title:         { type: string }
    description:   { type: clob } 

