detect_relations: true

Client:
  actAs: [Timestampable]
  columns: 
    id:           { type: integer, primary: true, autoincrement: true }
    user_id:      { type: integer(255) }
    track_record: { type: clob }
  relations: 
    User:
      class: sfGuardUser
      local: user_id
      foreign: id
      type: one
      foreignType: one
      foreignAlias: Client
      onDelete: cascade

Staff:
  actAs: [Timestampable]
  columns:
    id:               { type: integer, primary: true, autoincrement: true }
    user_id:          { type: integer(255) }
    title:            { type: string(255) }
    bio:              { type: clob }
    is_subcontractor: { type: boolean, notnull: true, default: 0 }
  relations:
    User:
      class: sfGuardUser
      local: user_id
      foreign: id
      type: one
      foreignType: one
      foreignAlias: Staff

StaffTaskWork:
  columns:
    staff_id:     { type: integer, notnull: true }
    task_work_id: { type: integer, notnull: true }

Account:
  actAs: [Timestampable]
  columns:
    id:           { type: integer, primary: true, autoincrement: true }
    client_id:    { type: integer }    
    plan_id:      { type: integer }
    title:        { type: string(255) }
    domain_name:  { type: string(255) }
    description:  { type: clob }
    active:       { type: boolean, notnull: true, default: 0 }

AccountRate:
  columns:       
    id:           { type: integer, primary: true, autoincrement: true }
    account_id:   { type: integer, notnull: true }
    task_work_id: { type: integer, notnull: true }
    title:        { type: string(255) }
    description:  { type: clob }
    hour_qouta:   { type: decimal } 
    rate_before:  { type: decimal }
    rate_after:   { type: decimal }
    
Credential:
  actAs: [Timestampable]
  columns:
    id:                 { type: integer, primary: true, autoincrement: true }
    account_id:         { type: integer, notnull: true }  
    credential_type_id: { type: integer, notnull: true }
    name:               { type: string(255) }
    internal_ip:        { type: string(255) }
    external_ip:        { type: string(255) }
    device:             { type: string(255) }
    url:                { type: string(255) }
    user:               { type: string(255) }
    pass:               { type: string(255) }
    notes:              { type: clob } 

CredentialType:
  columns: 
    id:   { type: integer, primary: true, autoincrement: true }
    name: { type: string(255) } 

AccountPlan:
  actAs: [Timestampable]
  columns: 
    account_id: { type: integer, notnull: true }
    plan_id:    { type: integer, notnull: true }

Plan:
  columns:
    id:          { type: integer, primary: true, autoincrement: true }
    title:       { type: string(255) }
    description: { type: clob }
    deduction:   { type: decimal }
    period_id:   { type: integer }

Period:
  columns:
    id:          { type: integer, primary: true, autoincrement: true }
    title:       { type: string(255) }
    description: { type: clob }
    days:        { type: integer }

Deduction:
  actAs: [Timestampable]
  columns:
    id:          { type: integer, primary: true, autoincrement: true }
    account_invoice_id: { type: integer, notnull: true }
    title:       { type: string(255) }
    description: { type: clob }
    deduction:   { type: decimal }
    approved:    { type: boolean, notnull: true, default: 1 }

AccountInvoice:
  actAs: [Timestampable]
  columns:
    id:          { type: integer, primary: true, autoincrement: true }
    account_id:  { type: integer }
    ref_no:      { type: string(255), unique: true }
    description: { type: clob }
    paid_off:    { type: boolean, notnull: true, default: 0 }
    is_viewable: { type: boolean, notnull: true, default: 0 }
  relations:
    Tasks: 
      refClass: AccountInvoiceTask
      class: Task
      foreignAlias: AccountInvoice

AccountInvoiceTask:
  columns: 
    account_invoice_id: { type: integer, notnull: true }
    task_id :           { type: integer, notnull: true }
  relations: 
    AccountInovice:
      foreignAlias: AccountInoviceTask 
    Task:
      foreignAlias: AccountInvoiceTask

AccountRecord:
  actAs: [Timestampable]
  columns: 
    id:          { type: integer, primary: true, autoincrement: true }
    account_id:  { type: integer }
    name:        { type: string(255), notnull: true }
    description: { type: clob }

Task:
  actAs: [Timestampable]
  columns: 
    id:               { type: integer, primary: true, autoincrement: true }
    account_id:       { type: integer, notnull: true }
    staff_id:         { type: integer } 
    task_status_id:   { type: integer, notnull: true }
    task_type_id:     { type: integer, notnull: true }
    task_priority_id: { type: integer, notnull: true }
    task_work_id:     { type: integer, notnull: true }
    ref_no:           { type: string(255), unique: true }
    name:             { type: string(255) }
    description:      { type: clob } 

TaskStatus:
  columns:
    id:           { type: integer, primary: true, autoincrement: true }
    name:         { type: string(255) }

TaskType:
  columns:
    id:           { type: integer, primary: true, autoincrement: true }
    name:         { type: string(255) }

TaskPriority:
  columns:
    id:           { type: integer, primary: true, autoincrement: true }
    name:         { type: string(255) }

TaskWork:
  columns:
    id:           { type: integer, primary: true, autoincrement: true }
    name:         { type: string(255) }
    rate:         { type: decimal }
    description:  { type: clob }

TaskComment:
  actAs: [Timestampable] 
  columns:
    id:           { type: integer, primary: true, autoincrement: true }
    task_id:      { type: integer, notnull: true }
    staff_id:     { type: integer, notnull: true } 
    title:        { type: string(255) }
    comment:      { type: clob }

TaskLog:
  actAs: [Timestampable]
  columns:
    id:            { type: integer, primary: true, autoincrement: true }
    task_id:       { type: integer, notnull: true }
    task_work_id:  { type: integer, notnull: true }
    staff_id:      { type: integer, notnull: true }
    title:         { type: string(255) }
    description:   { type: clob }
    gen_desc_id:   { type: integer }
    staff_comment: { type: clob }
    clock_in:      { type: timestamp }
    clock_out:     { type: timestamp } 
    hours_logged:  { type: decimal }
    mileage:       { type: decimal }
    percentage:    { type: integer }
    is_billable:   { type: boolean, notnull: true, default: 1 }
    is_viewable:   { type: boolean, notnull: true, default: 0 }
    
GenDesc:
  columns:
    id:            { type:integer, primary: true, autoincrement: true }
    title:         { type: string }
    description:   { type: clob } 

