generator:
  class: sfDoctrineGenerator
  param:
    model_class:           AccountRecord
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          account_record
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Record Management
        display: [name,account]
      filter:  ~
      form:    ~
      edit:
        title: Editing Record '%%name%%'
      new:
        title: Record Creation
